Add -pthread to {C,CXX} flags
Without -pthread the libraries won't link on Fedora because the linker
can't resolve references to pthread_key_delete:

/bin/ld: ../sevent/libsevent.a(Facade.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
/bin/ld: note: 'pthread_key_delete@@GLIBC_2.2.5' is defined in DSO /lib64/libpthread.so.0 so try adding it to the linker command line
/lib64/libpthread.so.0: could not read symbols: Invalid operation